import React from "react";
import { AbsoluteFill, Audio, Sequence, staticFile } from "remotion";

import "./fonts";
import { SCENES, framesOf, startOf } from "./theme";
import { Backdrop } from "./ui";
import { Access } from "./scenes/Access";
import { AgentScene } from "./scenes/Agent";
import { ChainsScene } from "./scenes/Chains";
import { Cta } from "./scenes/Cta";
import { StackScene } from "./scenes/Stack";
import { Wordmark } from "./scenes/Wordmark";

/**
 * The 30-second cut.
 *
 * Six scenes, back to back, over one continuous backdrop. The backdrop sits
 * outside the sequences so its glow drifts across the whole runtime instead of
 * restarting at every cut — that continuity is what stops six full-frame scenes
 * from reading as six separate cards.
 *
 * `from` and `durationInFrames` are both derived from the SCENES table in
 * theme.ts rather than written here. Writing them by hand is how a scene ends up
 * one frame short and a black seam appears mid-video, which is invisible while
 * scrubbing and obvious at speed.
 *
 * Each scene is `position: absolute; inset: 0` via SceneFade, so the 8-frame
 * out-fade of one overlaps nothing — the cuts are hard, with just enough of a
 * ramp to take the edge off. Cross-dissolving instead would need the sequences to
 * overlap, and at these durations a dissolve eats a noticeable share of a scene
 * that only has four seconds to make its point.
 */
export const Launch: React.FC = () => {
  const at = (id: (typeof SCENES)[number]["id"]) => ({
    from: startOf(id),
    durationInFrames: framesOf(id),
  });

  return (
    <AbsoluteFill style={{ backgroundColor: "#000000" }}>
      {/* The bed is generated to exactly 900 frames with its accents already on the
          scene boundaries, so it goes in at the root with no trimming and no
          volume ramp — the fades are baked into the file. See
          scripts/gen-audio.mjs. It is regenerated by `npm run render`; the .wav
          itself is gitignored because it is reproducible byte-for-byte. */}
      <Audio src={staticFile("bed.wav")} />
      <Backdrop />

      <Sequence {...at("wordmark")} name="Wordmark">
        <Wordmark />
      </Sequence>
      <Sequence {...at("access")} name="Access code">
        <Access />
      </Sequence>
      <Sequence {...at("agent")} name="Agent">
        <AgentScene />
      </Sequence>
      <Sequence {...at("stack")} name="Stack">
        <StackScene />
      </Sequence>
      <Sequence {...at("chains")} name="Networks">
        <ChainsScene />
      </Sequence>
      <Sequence {...at("cta")} name="CTA">
        <Cta />
      </Sequence>
    </AbsoluteFill>
  );
};
